#!/bin/bash
#module load mpi/openmpi/3.1
module load mpi/impi/2018
export I_MPI_HYDRA_BRANCH_COUNT=-1


path=DummyPath
executable="../build/src/executables/hQuicksort"
size=400000
stringLength=500
numberOfIterations=5
samplingFactor=2
dToNRatio=0.5
generator=2

mpiexec.hydra -bootstrap slurm $executable --size $size --stringLength $stringLength --numberOfIterations $numberOfIterations --dToNRatio $dToNRatio  --generator $generator --strongScaling --path $path
#mpirun --bind-to core --map-by core  $executable --size $size --stringLength $stringLength --numberOfIterations $numberOfIterations --dToNRatio $dToNRatio  
